services:
  - type: web
    name: thanzi-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python thanzi.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
